### ISSUE TITLE
Select number of days selected from current date

### ISSUE THREAD

**Issue by happiehappie** [hons82/THCalendarDatePicker#38]
Would be great if the calendar can have a new feature to only allow selection of up to n days(example 30 days) from current date. I only see disable future selection, which upon toggled every upcoming days can't be selected

**Comment by hons82** [comment]
Currently the futureselection/historyselection switch is just a Boolean because I never thought about adding such a feature...
Actually the only way to introduce this behaviour would be to switch to a Integer and use it like
- negative: enabled
- zero: disabled
- positive: would be the number of days allowed (future or history)
Reasonable?

**Comment by hons82** [comment]
Actually I did it now with an ```NSUInteger``` so I can use
- 0 = No restriction
- 1 = restricted = no day in future/history can be selected
- any positive number x = x days in future/history including today = today + (x-1) days

give it a try

**Comment by happiehappie** [comment]
Thanks, it works! :) Starred. Sincerely appreciate the swift response

**Comment by happiehappie** [comment]
Will you implement like, disabledDay in the future? For example Saturday + Sunday not selectable

**Comment by hons82** [comment]
Actually I haven't planned to do something like that...
Let me think about it, maybe I can come up with an acceptable solution.

Regarding swift: I'm working on a sample

**Comment by happiehappie** [comment]
Sorry, no pun intended, "Sincerely appreciate the swift response" I simply want to thank you for responding to me so quickly XD
Starred btw :)

**Comment by hons82** [comment]
THX
